version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - infra

  mongo:
    image: mongo:3.6
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - infra

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./es:/usr/share/elasticsearch/data
    networks:
      - infra

networks:
  infra:
    name: infra
    driver: bridge
