version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - cdn

  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - cdn
      - webapp

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./es:/usr/share/elasticsearch/data
    networks:
      - cdn
      - webapp

networks:
  cdn:
    driver: bridge
  webapp:
    driver: bridge
